title: tu ayuda ia
description: "Las mejores herramientas de inteligencia artificial, gratis y sin internet."
github_username: riwam
url: "https://riwam.github.io"

# TEMA: Este es el que da el diseño bonito
theme: minima

# Plugins necesarios para que todo funcione
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

# Configuración del marcado y resaltado de código
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
